### ISSUE TITLE
Epic: ACVM.js MVP release

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm-simulator#46]
# Features

- Users should be able to take either an initial witness or inputs/abi and generate a full witness for their circuit.
- Should be usable from both nodejs and the browser

```[tasklist]
### MVP
- [ ] #40
- [ ] https://github.com/noir-lang/acvm-simulator/issues/14
- [ ] https://github.com/noir-lang/acvm-simulator/issues/54
- [ ] https://github.com/noir-lang/acvm-simulator/issues/70
```

**Comment by Savio-Sou** [comment]
We can do a first release once https://github.com/noir-lang/acvm-simulator/issues/40 is in where people can start using it in Chromium-based browsers imo.

https://github.com/noir-lang/noir/issues/2811 is great to have but not critically needed in an MVP release.

**Comment by TomAFrench** [comment]
I've created a [milestone](https://github.com/noir-lang/acvm-simulator/milestone/1) for the remaining issues before release

**Comment by Savio-Sou** [comment]
@TomAFrench is this wrapped / up-to-date?

**Comment by TomAFrench** [comment]
This repository isn't going to be used for development anymore as this is being merged in to the main ACVM repo. We should make the release from there as the current code is out of sync with Noir.
